export interface Daily {
    total_orders: number,
    total_aov: number,
    total_revenue: number,
    top_sellers: TopSellers[],
    total_sessions: number,
    total_carts: number,
    total_checkouts: number,
}

export interface DailyFunnel {
    total_funnel_orders: number,
    total_funnel_sales: number,
    total_funnel_aov: number,
    total_opt_ins: number,
    total_upsell: number,
    total_downsell: number,
    order_page_views: number,
    order_unique_page_views: number,
    order_opt_ins: number,
    order_opt_in_rate: number,
    order_sales_count: number,
    order_sales_rate: number,
    order_sales_value: number,
    order_recurring_count: number,
    order_recurring_value: number,
    order_earnings: number,
    order_earnings_unique: number,
    upsell_page_views: number,
    upsell_unique_page_views: number,
    upsell_opt_ins: number,
    upsell_opt_in_rate: number,
    upsell_sales_count: number,
    upsell_sales_rate: number,
    upsell_sales_value: number,
    upsell_recurring_count: number,
    upsell_recurring_value: number,
    upsell_earnings: number,
    upsell_earnings_unique: number,
    confirm_page_view: number,
    confirm_unique_page_view: number,
    updated_at: any,
    created_at: any,
}

export interface TopSellers {
    title: string,
    count: number,
    id?: number
}


export interface Analytics {
    total_funnel_orders: number,
    total_funnel_sales: number,
    total_funnel_aov: number,
    total_opt_ins: number,
    total_upsell: number,
    total_downsell: number,
    order_page_views: number,
    order_unique_page_views: number,
    order_opt_ins: number,
    order_opt_in_rate: number,
    order_sales_count: number,
    order_sales_rate: number,
    order_sales_value: number,
    order_recurring_count: number,
    order_recurring_value: number,
    order_earnings: number,
    order_earnings_unique: number,
    upsell_page_views: number,
    upsell_unique_page_views: number,
    upsell_opt_ins: number,
    upsell_opt_in_rate: number,
    upsell_sales_count: number,
    upsell_sales_rate: number,
    upsell_sales_value: number,
    upsell_recurring_count: number,
    upsell_recurring_value: number,
    upsell_earnings: number,
    upsell_earnings_unique: number,
    updated_at: any,
    created_at: any,
}